// Turns the owner-edited product list (src/data/products.ts) into the shape
// the gallery components consume. Developers edit this file; the shop owner
// never needs to.
import { site, waLink } from "@/lib/site"
import {
  products as entries,
  SHOW_SOLD_OUT_ITEMS,
  type SectionId,
} from "@/data/products"
import sofaLqip from "./sofa-lqip.json"
import fridgeLqip from "./fridge-lqip.json"
import ovenLqip from "./oven-lqip.json"
import washerLqip from "./washing-machine-lqip.json"
import wardrobeLqip from "./wardrobe-lqip.json"

export interface Product {
  id: string
  name: string
  /** Top-level section, e.g. "sofas". Decides which page the product is on. */
  section: SectionId
  /** Filter group inside the section ("l-shaped", "silver", …). May be "". */
  type: string
  /** Cleaned / studio photos. First entry is the card hero. May be empty. */
  images: string[]
  /** Real, untouched photos. May be empty if none exist yet. */
  realPhotos: string[]
  /** Price in AED, or null when unknown — never invent one. */
  price: number | null
  /** Previous price in AED, shown struck through next to `price`. */
  oldPrice: number | null
  condition: string | null
  description: string | null
  featured: boolean
  available: boolean
  /** Custom WhatsApp inquiry text; null = the default message. */
  whatsappMessage: string | null
  /** Tiny blur-up placeholder for the hero image. */
  lqip?: string
}

// Blur-up placeholders, keyed by product id. Generated by
// scripts/optimize-images.py — new products simply have none (that's fine).
const LQIP: Record<string, { lqip: string }> = {
  ...sofaLqip,
  ...fridgeLqip,
  ...ovenLqip,
  ...washerLqip,
  ...wardrobeLqip,
}

/** Every product, normalised, in the order written in src/data/products.ts.
 *  Sold-out items are removed here when SHOW_SOLD_OUT_ITEMS is false. */
export const catalog: Product[] = entries
  .map((e) => ({
    id: e.id,
    name: e.name,
    section: e.section,
    type: e.type ?? "",
    images: e.images ?? [],
    realPhotos: e.realPhotos ?? [],
    price: e.price ?? null,
    oldPrice: e.oldPrice ?? null,
    condition: e.condition ?? null,
    description: e.description ?? null,
    featured: e.featured ?? false,
    available: e.available ?? true,
    whatsappMessage: e.whatsappMessage ?? null,
    lqip: LQIP[e.id]?.lqip,
  }))
  .filter((p) => SHOW_SOLD_OUT_ITEMS || p.available)

/** Products belonging to one section/page, in catalog order. */
export function productsBySection(section: SectionId): Product[] {
  return catalog.filter((p) => p.section === section)
}

// Catch the most common data-entry mistake (a copy-pasted duplicate id)
// during local development without breaking the live site.
if (import.meta.env.DEV) {
  const seen = new Set<string>()
  for (const e of entries) {
    if (seen.has(e.id))
      console.warn(
        `[products] Duplicate product id "${e.id}" in src/data/products.ts — ids must be unique.`
      )
    seen.add(e.id)
  }
}

/** Hero image for a card / the default modal image. */
export function heroImage(p: Product): string | undefined {
  return p.images[0] ?? p.realPhotos[0]
}

/** "AED 1,250" — currency comes from src/lib/site.ts. */
export function formatPrice(amount: number): string {
  return `${site.currency} ${amount.toLocaleString()}`
}

function inquiryText(p: Product): string {
  return (
    p.whatsappMessage ??
    `Hello, I am interested in this item: ${p.name} (${p.id}). Is it available?`
  )
}

/** Deep link that opens the product's section page with its details popup
 *  already open (the gallery reads the ?item= query param on load). */
export function productUrl(p: Product): string {
  return `/${p.section}?item=${encodeURIComponent(p.id)}`
}

/**
 * Open a WhatsApp chat to our business number, pre-filled with the inquiry and
 * a link straight to the product. WhatsApp deep links can target a specific
 * number (so it always reaches us) but can't attach anything, so we include
 * the product's page URL in the text — tapping it opens the website with that
 * product's popup (photos, price, contact buttons) already showing.
 */
export function shareProduct(p: Product): void {
  const base = inquiryText(p)
  const absUrl =
    typeof window !== "undefined"
      ? new URL(productUrl(p), window.location.origin).href
      : undefined
  const text = absUrl ? `${base}\n${absUrl}` : base
  window.open(waLink(text), "_blank", "noopener,noreferrer")
}
